spring:
  freemarker:
    enabled: true

# Discovery Server Setup
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5         # DO NOT DO THIS IN PRODUCTION
  client:
    registerWithEureka: false
    fetchRegistry: false

# HTTP Server
server:
  port: 1111