# Spring properties
spring:
  application:
    name: order-capture
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    freemarker:
      enabled: false

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5         # DO NOT DO THIS IN PRODUCTION

# HTTP Server
server:
  port: 3333